USE `pantera_db`.`paises`;
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ad", "Andorra");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ae", "Emiratos Árabes Unidos");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("af", "Afganistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ag", "Antigua y Barbuda");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ai", "Anguila");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("al", "Albania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("am", "Armenia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ao", "Angola");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ar", "Argentina");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("as", "Samoa Americana");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("at", "Austria");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("au", "Australia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("az", "Azerbaiyán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ba", "Bosnia-Herzegovina");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bb", "Barbados");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bd", "Bangladés");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("be", "Bélgica");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bf", "Burkina Faso");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bg", "Bulgaria");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bh", "Baréin");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bi", "Burundi");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bj", "Benín");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bm", "Bermudas");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bn", "Brunéi");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bo", "Bolivia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("br", "Brasil");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bs", "Bahamas");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bt", "Bután");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bw", "Botsuana");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("by", "Bielorrusia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("bz", "Belice");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ca", "Canadá");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cd", "República Democrática del Congo");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cf", "República Centroafricana");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cg", "República del Congo");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ch", "Suiza");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ci", "Costa de Marfil");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cl", "Chile");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cm", "Camerún");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cn", "República Popular China");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("co", "Colombia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cr", "Costa Rica");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cu", "Cuba");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cy", "Chipre");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("cz", "Chequia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("de", "Alemania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("dj", "Yibuti");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("dk", "Dinamarca");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("dm", "Dominica");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("do", "República Dominicana");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("dz", "Argelia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ec", "Ecuador");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ee", "Estonia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("eg", "Egipto");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("er", "Eritrea");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("es", "España");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("et", "Etiopía");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("fi", "Finlandia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("fj", "Fiyi");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("fr", "Francia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ga", "Gabón");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gd", "Granada");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ge", "Georgia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gf", "Guayana Francesa");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gh", "Ghana");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gl", "Groenlandia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gm", "Gambia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gn", "Guinea");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gq", "Guinea Ecuatorial");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gr", "Grecia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gw", "Guinea-Bisáu");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("gy", "Guyana");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("hk", "Hong Kong");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("hn", "Honduras");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("hr", "Croacia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ht", "Haití");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("hu", "Hungría");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("id", "Indonesia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ie", "Irlanda");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("il", "Israel");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("in", "India");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("iq", "Irak");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ir", "Irán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("is", "Islandia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("it", "Italia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("jm", "Jamaica");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("jo", "Jordania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("jp", "Japón");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ke", "Kenia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("kg", "Kirguistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("kh", "Camboya");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ki", "Kiribati");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("kp", "Corea del Norte");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("kr", "Corea del Sur");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("kw", "Kuwait");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("kz", "Kazajistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("la", "Laos");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("lb", "Líbano");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("li", "Liechtenstein");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("lk", "Sri Lanka");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("lr", "Liberia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ls", "Lesoto");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("lt", "Lituania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("lu", "Luxemburgo");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("lv", "Letonia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ly", "Libia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ma", "Marruecos");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mc", "Mónaco");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("md", "Moldavia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("me", "Montenegro");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mg", "Madagascar");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mk", "Macedonia del Norte");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ml", "Malí");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mm", "Birmania (Myanmar)");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mn", "Mongolia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mo", "Macao");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mr", "Mauritania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mt", "Malta");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mv", "Maldivas");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mw", "Malaui");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mx", "México");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("my", "Malasia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("mz", "Mozambique");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("na", "Namibia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ne", "Níger");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ng", "Nigeria");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ni", "Nicaragua");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("nl", "Países Bajos");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("no", "Noruega");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("np", "Nepal");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("nr", "Nauru");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("nz", "Nueva Zelanda");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("om", "Omán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pa", "Panamá");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pe", "Perú");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pg", "Papúa Nueva Guinea");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ph", "Filipinas");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pk", "Pakistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pl", "Polonia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pr", "Puerto Rico");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("pt", "Portugal");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("py", "Paraguay");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("qa", "Catar");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ro", "Rumania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("rs", "Serbia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ru", "Rusia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("rw", "Ruanda");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sa", "Arabia Saudita");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sd", "Sudán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("se", "Suecia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sg", "Singapur");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("si", "Eslovenia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sk", "Eslovaquia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sl", "Sierra Leona");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sm", "San Marino");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sn", "Senegal");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("so", "Somalia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sr", "Surinam");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sv", "El Salvador");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sy", "Siria");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("sz", "Suazilandia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("td", "Chad");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tg", "Togo");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("th", "Tailandia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tj", "Tayikistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tk", "Tokelau");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tl", "Timor Oriental");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tm", "Turkmenistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tn", "Túnez");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("to", "Tonga");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tr", "Turquía");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tt", "Trinidad y Tobago");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tv", "Tuvalu");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tw", "Taiwán (República de China)");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("tz", "Tanzania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ua", "Ucrania");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ug", "Uganda");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("uk", "Reino Unido");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("us", "Estados Unidos");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("uy", "Uruguay");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("uz", "Uzbekistán");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("va", "Ciudad del Vaticano");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ve", "Venezuela");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("vn", "Vietnam");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("vu", "Vanuatu");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ws", "Samoa");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("ye", "Yemen");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("za", "Sudáfrica");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("zm", "Zambia");
INSERT INTO `pantera_db`.`paises` (`cc`, `nombre`) VALUES ("zw", "Zimbabue");
